public/index.html
Change description and title of index.html
=> Change description and title

public/index.html, src/index.css, src/utils/activityPeriods.js
* Prevent horizontal scrolling 
* Prevent zooming (does not work on iOS unfortunately)
=> Prevent scrolling and zooming

package.json, src/App.css, src/App.js, src/components/ActivitySwitch.js, src/components/BottomNavBar.js, src/components/TimeOfService.js, src/components/Timeline.js, yarn.lock
Isolate styling in CSS files instead of using inline styles
=> Use css instead of inline styles

web/common/Header.js, web/common/routes.js
https://trello.com/c/Npls16Bb/373-rendre-plus-claires-les-cat%C3%A9gories-du-menu-de-navigation
Petites modifications UI sur le drawer menu.
Dans le fichier routes.js, j'ai dû rajouter des menus invisibles pour le logout et la page "Mes informations", à voir si on trouve une solution plus propre.
=> Change drawer menu : creating "Mon compte" sub menu

web/common/Comment.js, web/pwa/components/EndMission.js
https://trello.com/c/qnBKSrcq/374-uniformiser-le-nommage-des-observations-commentaires
=> Change "commentaire" to "observation"

common/utils/apiQueries.js, common/utils/mission.js, web/admin/components/MissionDetails.js, web/admin/components/styles/ValidationsStyle.js, web/admin/panels/Validations.js, web/admin/selectors/missionSelectors.js, web/admin/utils/loadCompaniesData.js, web/admin/utils/store.js
https://trello.com/c/TrgPS0ix/371-visualiser-les-missions-d%C3%A9j%C3%A0-valid%C3%A9es
Rajout d'un onglet pour visualiser les missions validées par un gestionnaire.
Peut être faut il du coup renommer le menu "Saisies à valider"...
=> Visualize missions validated by admin

common/utils/apiQueries.js, common/utils/errors.js, common/utils/loadUserData.js, common/utils/store.js, web/admin/panels/Company.js, web/admin/utils/store.js, web/common/EmploymentInfoCard.js, web/common/Header.js, web/control/UserRead.js, web/home/AccountInfo.js
Suppression de la distinction entre rattachement principal et rattachements secondaires.
Désormais dans la page "Mes informations" on affiche une liste unique des rattachements de l'utilisateur, sans distinction principal/secondaire
=> Control page - 2 - Feature/no primary employment

common/utils/activities.js, common/utils/apiQueries.js, package.json, web/admin/components/AugmentedTable.js, web/admin/components/MissionDetails.js, web/admin/components/WorkTimeDetails.js, web/admin/components/WorkTimeTable.js, web/admin/components/styles/WorkTimeDetailsStyle.js, web/admin/panels/Activities.js, web/admin/panels/Validations.js, web/admin/selectors/missionSelectors.js, web/pwa/components/ActivityList.js, yarn.lock
Rajout d'un Drawer pour afficher le détail d'une journée d'un salarié.
https://trello.com/c/zfO6xkYf/352-acc%C3%A9der-au-d%C3%A9tail-dune-journ%C3%A9e-de-travail-dun-salari%C3%A9
Couplé à la PR du back :
https://github.com/MTES-MCT/mobilic-api/pull/35
=> Accéder au détail d'une journée de travail d'un salarié

common/store/selectors.js, common/utils/apiQueries.js, common/utils/employments.js, common/utils/history/changePeriod.js, common/utils/history/computePeriodStatuses.js, common/utils/history/fillPeriods.js, common/utils/history/groupByPeriodUnit.js, common/utils/history/periodUnits.js, common/utils/regulation/alertTypes.js, common/utils/regulation/computeAlerts.js, common/utils/regulation/rules.js, common/utils/time.js, web/admin/components/SideMenu.js, web/common/DayRegulationInfo.js, web/common/EmploymentInfoCard.js, web/common/Header.js, web/common/TextWithBadge.js, web/control/UserRead.js, web/control/components/AlertGroup.js, web/control/components/RegulatoryAlert.js, web/control/components/UserReadAlerts.js, web/control/components/UserReadHistory.js, web/control/components/UserReadInfo.js, web/control/components/UserReadTabs.js, web/pwa/components/PeriodCarouselPicker.js, web/pwa/components/RegulationCheck.js, web/pwa/components/history/Week.js, web/pwa/screens/History.js
https://trello.com/c/1fKgHxhG/356-visualiser-la-liste-agr%C3%A9g%C3%A9e-des-infractions-de-la-p%C3%A9riode-contr%C3%B4l%C3%A9e
=> Control page - 4 - Feature/revamp control page

web/admin/components/AugmentedTable.js, web/admin/panels/Employees.js
https://trello.com/c/WqHH8Y8p/496-liste-des-salari%C3%A9s-tronqu%C3%A9e
Update scroll position of valid employees when scrolling pending invitations.
=> Fix of valid employees list display

web/admin/components/ActivitiesCard.js, web/admin/components/styles/ActivitiesCardStyle.js
If number of activities is below a threshold => no accordion
If above threshold => accordion
expanded if Already validated
Icons issue ??
=> accordion or not depending on number of activities

common/utils/matomoTags.js, package.json, web/admin/components/ActivitiesCard.js, web/admin/components/MissionDetails/MissionDetails.js, web/admin/components/MissionNamesList.js, web/admin/components/PeriodToggle.js, web/admin/components/WorkDayEndTime.js, web/admin/components/WorkTimeDetails.js, web/admin/components/WorkTimeTable.js, web/admin/panels/Activities.js, web/admin/panels/Validations.js, yarn.lock
Added some events for tracking user navigation in Matomo
https://trello.com/c/1AZCaYx3/480-rajouter-des-tags-dans-le-site-pour-tracer-les-actions-utilisateurs
=> Add Matomo tags for admin site

web/landing/ResourcePage/AdminResourcePage.js, web/landing/ResourcePage/DriverResourcePage.js
Mise à jour des modes opératoires gestionnaire et travailleur mobile
=> Maj Modes opératoires mars 2022

README.md, public/cgu.md
Little PR as we have moved our DB from OVH to Scalingo
=> Change OVH to Scalingo

web/admin/components/C1BExport.js, web/admin/components/ExcelExport.js, web/admin/panels/Activities.js
Afin de ne pas mélanger les infos de plusieurs sociétés dans un même fichier excel, plutôt que de faire un fichier par entreprise, il a été décidé de ne pouvoir choisir qu'une société à la fois.
https://trello.com/c/yJxnb7hq/615-refonte-apparence-onglet-activit%C3%A9s-de-lexport-xls
=> Only one company is selectable in XLS export

common/utils/time.js, web/pwa/components/PDFExport.js
Trello: https://trello.com/c/VaisrLYn/618-modification-de-lexport-pdf-mensuel
PR Back: https://github.com/MTES-MCT/mobilic-api/pull/69
=> send today as max_date if we choose current month as last month

web/admin/Admin.js
https://trello.com/c/kbr76KKY/631-bug-etq-gestionnaire-reload-page-apres-validation-de-mission
=> Only refresh current company data when a refresh is needed.

README.md
https://trello.com/c/dbB4YDrj/587-ajout-du-kit-de-com-interfa%C3%A7age-en-libre-service-dans-la-doc-api
=> chore(readme): add integration conditions link

common/utils/actions.js, common/utils/loadUserData.js, web/common/NewMissionForm.js, web/common/VehicleField.js, web/pwa/components/DriverSelection.js, web/pwa/components/VehicleFieldForApp.js
https://trello.com/c/7P8pbIrd/346-pr%C3%A9-remplir-le-kilom%C3%A9trage-de-d%C3%A9but-avec-la-derni%C3%A8re-valeur-de-kilom%C3%A9trage-connue-pour-le-v%C3%A9hicule
Préremplissage du kilométrage d'un véhicule au début d'une mission.
PR back : https://github.com/MTES-MCT/mobilic-api/pull/78
=> Prefill kilometer reading for vehicle when starting a mission

web/admin/components/AugmentedTable.js
https://trello.com/c/F2CCO4Uy/709-bug-graphique-dans-saisies-%C3%A0-valider
=> added a bit more height in virtualized table

web/pwa/components/Expenditures.js
https://trello.com/c/qfJJaXh2/612-saisie-des-frais-pour-une-mission-%C3%A0-cheval-sur-2-jours
=> check only first day by default

web/landing/ResourcePage/ResourcePage.js
https://trello.com/c/ACYNMdlu/707-mise-%C3%A0-jour-des-notices-dutilisation-gestionnaire-et-contr%C3%B4leur
=> new versions documents

common/utils/api.js, common/utils/history/changePeriod.js, web/admin/components/AugmentedTable.js
https://trello.com/c/gfActztK/721-bugs-fronts-audit-mte
=> fix: sonar bugs

web/control/components/UserReadInfo.js
https://trello.com/c/HjgeL1af/636-vue-synth%C3%A9tique-de-la-mission-en-cours-v%C3%A9hicule-utilis%C3%A9e-dans-longlet-informations-message-attention-pas-de-mission-en-cours-30
=> Show vehicle information in controls

web/controller/components/home/ControllerHome.js
https://trello.com/c/rYfVkUaf/750-v0-lic-papier-pr%C3%A9sent%C3%A9-et-pas-de-lic-%C3%A0-bord
=> feat: add modal in construction

common/utils/apiQueries.js, common/utils/time.js, web/control/UserRead.js, web/control/components/UserReadInfo.js, web/controller/components/details/ControllerControlDetails.js, web/controller/components/details/ControllerControlDrawer.js, web/controller/components/details/ControllerControlHeader.js, web/controller/components/home/ControllerHome.js, web/controller/components/scanQRCode/ControllerScanQRCode.js
https://trello.com/c/Dk6fjo3v/753-acc%C3%A9der-%C3%A0-un-contr%C3%B4le-dans-le-nouveau-parcours-contr%C3%B4leur
Pour l'instant, la seule façon d'afficher le drawer sans toucher le code, c'est de scanner un code.
Sinon, il faut forcer le controlIdOnFocus à l'initialisation avec un controlId existant en base dans le composant ControllerHome
PR back : https://github.com/MTES-MCT/mobilic-api/pull/101
=> Be able to view control data in controller interface

web/admin/panels/Company.js, web/admin/panels/Employees.js, web/admin/panels/KnownAddresses.js, web/admin/panels/Vehicles.js
https://trello.com/c/QokSayPT/611-tchat-crisp-qui-cache-le-menu-des-employ%C3%A9s
J'ai hésité entre réduire juste les tableaux, ou tout le container... Je suis ouvert au changement si besoin.
=> Put margin on right to avoid conflict with Crisp

common/utils/loadUserData.js, web/admin/components/AugmentedTable.js, web/admin/components/AugmentedTableHeaderCellContent.js, web/admin/panels/KnownAddresses.js, web/admin/store/reducers/sync.js
https://trello.com/c/Bpcch0lJ/735-trier-les-adresses-pr%C3%A9-enregistr%C3%A9es-par-ordre-alphab%C3%A9tique
=> Fix be able to sort an address by name + default sort by name

common/utils/apiQueries.js, web/controller/components/details/ControllerControlDetails.js, web/controller/components/list/ControlsList.js, web/controller/components/list/table/ControlsTable.js
https://trello.com/c/bmC0Stb9/760-nombre-de-jours-contr%C3%B4l%C3%A9s-contr%C3%B4les
=> retrieve nb controlled days and show it in history table

package.json, scripts/build.js
run `npm run build-analyze` to see a visualization of generated bundles
=> added npm run build-analyze

common/utils/matomoTags.js, web/admin/components/MissionDrawer.js
https://trello.com/c/SybfZnqU/702-matomo-modifications-admin-temporaires
Rajout de 2 events Matomo
=> Add Matomo event when cancelling update on mission

common/utils/contradictory.js, web/admin/components/MissionEmployeeCard.js, web/common/Event.js, web/common/MissionValidationInfo.js, web/common/logEvent.js, web/pwa/components/ContradictoryChanges.js, web/pwa/components/MissionDetails.js, web/pwa/components/history/Mission.js
https://trello.com/c/jHAU5UgV/522-adapter-lhistorique-de-saisie
Pour voir ce qui a été fait, cf les deux § "solutions" de description du ticket
=> Revamp mission events timeline

web/pwa/components/history/Mission.js
https://trello.com/c/muYBIzir/784-etq-contr%C3%B4leur-je-ne-dois-pas-pouvoir-modifier-le-v%C3%A9hicule-dune-mission
=> Fix : a vehicle should not be editable during a control.

web/control/components/UserReadInfo.js
https://trello.com/c/dGYjTmbN/797-ne-pas-afficher-lid-mobilic-du-salari%C3%A9
=> feat(control): remove mobilic id

common/utils/apiQueries.js, web/common/EmploymentInfoCard.js
https://trello.com/c/iYsNTgtB/777-etq-contr%C3%B4leur-je-vois-le-nom-officiel-de-lentreprise-en-plus-du-nom-usuel-saisi-par-le-gestionnaire
=> feat(control): display company legal name

web/controller/components/details/ControllerControlHeader.js, web/controller/components/home/ControllerHome.js, web/controller/components/scanQRCode/ControllerScanQRCode.js
https://trello.com/c/zApdyt3k/809-augmenter-lespace-avant-les-liens
=> fix(controller): add spacing around links

web/admin/panels/Employees.js
https://trello.com/c/0BVuxsWN/787-modifier-acc%C3%A8s-gestionnaire-des-salari%C3%A9s-invit%C3%A9s
=> feat: add/remove admin right to guest users

web/common/TimezoneSelect.js
https://trello.com/c/lpVYNPJr/710-avertir-de-mani%C3%A8re-automatis%C3%A9e-les-entreprises-guyanaises-du-probl%C3%A8me-de-fuseau-horaire-dans-mobilic
=> feat: add info for guyana timezone

common/utils/errors.js, web/common/Snackbar.js
Pour diagnostiquer https://trello.com/c/rvfxY4fo/861-lexport-excel-ne-fonctionne-plus
=> chore: add logs to debug

web/root.js
https://trello.com/c/EF1HP7II/819-mot-en-anglais-%C3%A0-remplacer-dans-linterface-contr%C3%B4leur
=> feat: use fr text for mui components

web/pwa/screens/History.js
https://trello.com/c/tXWbnVdz/654-cta-t%C3%A9l%C3%A9chargement-pdf-peu-intuitif
=> feat(history): add label to download pdf

web/control/UserReadQRCode.js
https://trello.com/c/A4L9jjxO/643-corriger-lespace-dans-la-modale-acc%C3%A8s-contr%C3%B4leurs-qr-code
=> Less space between title and QR Code modal content

common/assets/styles/root.scss, common/utils/apiQueries.js, web/common/TimezoneSelect.js, web/common/WayHeardOfMobilic.js, web/signup/AccountCreation.js, web/signup/EmailSelection.js
https://trello.com/c/MjSgMqxZ/697-ajouter-une-ligne-comment-avez-vous-connu-mobilic-dans-le-formulaire-dinscription
=> Add component to know how admin had heard of Mobilic

web/common/routes.js, web/landing/partners.js
https://trello.com/c/tlFno5Z2/871-affichage-des-logos-partenaires-en-prod-version-mobile
=> Lien Partenaires en vue mobile

common/utils/apiQueries.js, web/admin/panels/Employees.js
https://trello.com/c/RCsaVZCH/813-afficher-le-mail-des-salari%C3%A9s-dans-longlet-salari%C3%A9s
=> get emails from employments and display in admin table

common/components/App.js, common/utils/apiFragments.js, common/utils/apiQueries.js, common/utils/regulation/useGetUserRegulationComputationsByDay.js, web/admin/components/WorkTimeDetails.js, web/control/UserRead.js
https://trello.com/c/j0mwrW43/890-modifier-le-calcul-des-alertes-dans-la-fiche-du-jour-gestionnaire
=> Display regulatory computation from the backend in the daily view for managers

web/common/logEvent.js, web/pwa/components/ContradictoryChanges.js
https://trello.com/c/OYwxpeAz/803-probl%C3%A8me-de-tournure-des-phrases-dans-lhistorique-de-saisie
PR Back : https://github.com/MTES-MCT/mobilic-api/pull/143
=> One action can lead to multiple history entries

common/utils/actions.js, common/utils/apiQueries.js, web/admin/components/MissionDetails/MissionDetails.js, web/admin/panels/Validations.js, web/admin/store/reducers/mission.js, web/admin/utils/missionActions.js
https://trello.com/c/Z3nwzYl8/875-bug-db-%C3%A0-la-validation-dune-mission
PR BACK : https://github.com/MTES-MCT/mobilic-api/pull/142
=> Correction erreur db lorsqu'il y avait des modifications gestionnaires sur une mission en équipe

common/utils/errors.js, web/admin/panels/KnownAddresses.js
PR back : https://github.com/MTES-MCT/mobilic-api/pull/140
Trello : https://trello.com/c/OGQryuFo/872-suppression-doublon-dans-table-address
=> fix: dislay error on company address creation

web/admin/panels/Employees.js
https://trello.com/c/PsHzFq7L/931
=> Set new employee default rights.

common/utils/time.js
https://trello.com/c/Kg0yLM2h/934-cadeau-de-no%C3%ABl-de-marie-mettre-au-singulier-heure-et-minute-dans-le-d%C3%A9compte-des-activit%C3%A9s-quand-cest-n%C3%A9cessaire
=> Pluralize time duration words

common/utils/apiQueries.js, common/utils/loadUserData.js, web/common/EmploymentInfoCard.js, web/common/ThirdPartyEmploymentAccess.js
Trello: https://trello.com/c/5EcvuPUd/951-affichage-du-lien-employment-logiciel
PR back: https://github.com/MTES-MCT/mobilic-api/pull/153
=> Feat: display access software

common/utils/apiQueries.js, common/utils/errors.js, web/common/routes.js, web/login/SyncEmployeeValidation.js
https://trello.com/c/vgjcEBjS/949
=> Sync employee validation page

web/common/NewMissionForm.js
https://trello.com/c/3l2iJi2j/982
=> Prevent useless calls to address api.

common/utils/time.js, web/login/login.js
https://trello.com/c/DCxLLbAq/940
PR Back : https://github.com/MTES-MCT/mobilic-api/pull/162
=> Block account when too many bad pwd

config/env.js, public/index.html, web/admin/Admin.js
https://trello.com/c/Vwymjufq/965-mesure-dimpact-n3-nps-salari%C3%A9-gestionnaire
Pour que ça fonctionne, il faut rajouter la variable d'environnement SURVICATE_ACCOUNT_KEY côté front, avec la valeur mise dans la carte Trello
=> Add survicate NPS survey

web/common/NewPasswordBlock.js, web/login/ResetPassword.js, web/pwa/components/UpdatePassword.js
https://trello.com/c/DGKCJvGd/992-emp%C3%AAcher-de-valider-un-mot-de-passe-invalide
=> fix(reset password): deactivate button if error

common/utils/errors.js
https://trello.com/c/zPacrdHW/939-supprimer-message-sp%C3%A9cifique-si-on-veut-cr%C3%A9er-un-compte-avec-un-utilisateur-existant
=> Error message less specific when registering with existing email

common/utils/loadUserData.js
https://trello.com/c/YcSYh5Fw/991
=> Load coworker data in background

web/controller/components/history/ControllerHistory.js
https://trello.com/c/pqBkwljj/948-elargir-la-plage-dhistorique-des-contr%C3%B4les-par-d%C3%A9faut-%C3%A0-2-mois
set default start date to startOfMonth(Today - 31)
=> fix/Controller History default start date 

web/admin/components/AugmentedTable.js, web/admin/panels/KnownAddresses.js
https://trello.com/c/mdOtmGjs/1025-tri-dans-les-tableaux-insensibles-%C3%A0-la-casse
=> Sort by should be case insensitive in AugmentedTable.

common/components/App.js, common/store/store.js, common/utils/apiQueries.js, common/utils/history/changePeriod.js, common/utils/history/groupByPeriodUnit.js, common/utils/loadUserData.js, common/utils/mission.js, common/utils/regulation/useGetUserRegulationComputationsByDay.js, web/control/UserRead.js, web/control/components/UserReadHistory.js, web/pwa/components/PeriodFilter.js, web/pwa/screens/History.js
https://trello.com/c/fDO1u3b2/788-faire-passer-lhistorique-du-salari%C3%A9-%C3%A0-3-ans
Period filter was added on employee history (it should have no impact on logged and not logged controlers who are using same history component but without filter)
=> Increase employee history limit to 3 years

web/root.js
https://trello.com/c/sJfHEfiz/1014
=> XLS verify export page should be accessible for logged in controller

common/utils/loadUserData.js
Trello: https://trello.com/c/UanOxFLp/1005
PR back: https://github.com/MTES-MCT/mobilic-api/pull/182
=> feat: display team vehicle & address if applicable

web/pwa/components/PDFExport.js
https://trello.com/c/bB26lxv8/793
=> Should not be able to select more than 12 months when exporting data in pdf

web/pwa/components/PDFExport.js
https://trello.com/c/bUZuNF8m/977-limiter-le-calendrier-%C3%A0-3-ans
=> Should not be able to export data prior to 3 years

web/common/routes.js, web/landing/accessibility.js, web/landing/footer.js
https://trello.com/c/WQWAOq2z/1039
=> Add accessibility declaration

web/common/WayHeardOfMobilic.js
https://trello.com/c/OJI0j2Hm/1042
=> Add platform way of heard

common/utils/apiQueries.js, web/admin/Admin.js, web/admin/panels/CertificationPanel.js, web/admin/panels/Company.js, web/pwa/components/CertificationCommunicationModal.js
https://trello.com/c/AiY65dej/1060
(partie 3)
PR Back : https://github.com/MTES-MCT/mobilic-api/pull/205
=> Add certification panel

web/admin/panels/CompanyTeamCreationRevisionModal.js
https://trello.com/c/FaBi7n37/1084
=> Select current user as admin by default for new teams

common/components/LoadingButton.js, web/pwa/components/PDFExport.js
https://trello.com/c/8220JpMj/1061
=> Ability to have a label near circular progress in loading button

common/utils/apiQueries.js, web/common/EmploymentInfoCard.js
https://trello.com/c/JJAFXlhq/1074
PR Back : https://github.com/MTES-MCT/mobilic-api/pull/206
=> Add current admins in employment card in control

common/utils/apiQueries.js, common/utils/time.js, web/home/AccountInfo/AccountInfo.js, web/home/AccountInfo/UserControlSection.js
https://trello.com/c/XPktEreK/1033-section-contr%C3%B4les-en-bord-de-route
PR BACK : https://github.com/MTES-MCT/mobilic-api/pull/211
=> Add user controls section

web/login/ResetPassword.js
https://trello.com/c/fnL9awVm/1105-corriger-une-petite-typo
=> fixed typo

web/pwa/components/WorkTimeSummary.js
https://trello.com/c/WtE2xcH9/1029-bug-sur-le-recap-de-la-semaine-ou-du-mois-en-cours
=> Fix work time calculation when there is ongoing activity

web/pwa/components/PeriodFilter.js
https://trello.com/c/rH8EVOXp/1113-scroll-horizontal-sur-mobile
=> Fix bad scrolling in user history

web/admin/panels/Company.js
https://trello.com/c/flBlMFtr/1109-onglets-groupe-et-certificat-et-api-non-accessibles-sur-mobile-responsive-ko
=> Fix non responsive tabs in company panel

web/admin/panels/Activities.js, web/admin/store/reducers/sync.js, web/admin/store/reducers/team.js, web/admin/store/reducers/users.js, web/admin/store/store.js
https://trello.com/c/PV152DaU/1058-export-excel-avec-le-mode-groupe-cas-contr%C3%B4le-en-entreprise
=> All groups and users should be exportable

common/utils/apiQueries.js, web/admin/panels/CertificationPanel/CertificationPanel.js
https://trello.com/c/Ea1wHdij/1130-t%C3%A9l%C3%A9charger-un-certificat-pdf
PR Back : https://github.com/MTES-MCT/mobilic-api/pull/231
=> Add download certificate button

web/admin/panels/CertificationPanel/CertificationCriteriaGlobalResult.js, web/admin/panels/CertificationPanel/CertificationCriteriaSingleResult.js, web/admin/panels/CertificationPanel/CertificationPanel.js
https://trello.com/c/80335I7o/1139-affichage-des-crit%C3%A8res-dans-longlet-certificat-pour-le-cas-pas-encore-calcul%C3%A9
=> Display certificate criterias even when certificate is not yet calculated

common/utils/apiQueries.js, web/admin/panels/Employees.js, web/admin/panels/EmployeesTeamRevisionModal.js
https://trello.com/c/l8gUVTCA/1106-resoudre-bug-affectation-dun-invite
PR Back : https://github.com/MTES-MCT/mobilic-api/pull/233
=> Add ability to change a team of a pending employment

web/common/Header.js, web/common/routes.js
https://trello.com/c/8OeBRCGY/1131-etq-salari%C3%A9-je-trouve-plus-facilement-la-page-faq
=> FAQ before Documentation - Resources before Mon Compte

web/landing/ResourcePage/ControllerResourcePage.js, web/landing/ResourcePage/ResourcePage.js
https://trello.com/c/Zb92YF8p/1141-maj-de-la-documentation-ctt-it
=> feat(doc): update notice & video for controllers

web/controller/components/details/ControllerControlHeader.js, web/controller/components/noLic/ControllerControlNoLicDrawer.js
https://trello.com/c/n84DL7sp/1171-export-pas-de-lic
=> Should not be able to export no lic controls

web/admin/components/C1BExport.js
https://trello.com/c/CsY7xauF/996-export-c1b-des-donn%C3%A9es-apr%C3%A8s-validation-salari%C3%A9
https://github.com/MTES-MCT/mobilic-api/pull/254
=> Ability to retrieve employee version of C1B files

common/utils/apiFragments.js, web/controller/components/list/ControlsList.js, web/controller/components/list/table/ControlsTable.js
https://trello.com/c/yfHLNsQN/836-afficher-le-nombre-dinfractions-retenues-dans-lhistorique-des-contr%C3%B4les
=> retrieve number of reported infractions and display

web/regulatory/RegulatoryText.js
https://trello.com/c/BOIvKvcu/1164-ui-mettre-au-format-message-dinfo-lexplication-des-seuils-non-calcul%C3%A9s
=> feat(RegulatoryText): change threshold message format

web/controller/components/controlBulletin/ControlBulletinFormStep2.js
- change from "N° SIREN" to "SIREN ou Numéro TVA";
https://trello.com/c/o1wne3Rx/1199-modifier-wording-parcours-bdc
=> feat(BDC): change wording for SIREN

web/admin/panels/Company.js
https://trello.com/c/5phuE9Q2/1181-a%C3%A9rer-entre-le-titre-de-longlet-certificat-et-la-pastille
=> feat(company): change badge icon spacing for certificat

web/control/VerifyXlsxSignature.js
https://trello.com/c/mvaxp7Xh/1238-gestion-des-erreurs-lors-de-la-v%C3%A9rification-des-fichiers-excel
https://github.com/MTES-MCT/mobilic-api/pull/270
=> Fix error management when verifying excel file signature

web/control/components/RegulatoryAlert.js
https://trello.com/c/Op5oDsak/1168-relever-des-infractions-modifier-les-infractions-retenues-dans-le-parcours-qr-code
display more info about periods
=> display control day

web/control/components/RegulatoryAlert.js
- modify text after demo
https://trello.com/c/Op5oDsak/1168-relever-des-infractions-modifier-les-infractions-retenues-dans-le-parcours-qr-code
=> fix(infraction): modify infraction alert text

web/control/components/RegulatoryAlert.js
https://trello.com/c/uCfL2PzU/1249-wording-pour-infraction-sur-travail-de-nuit
=> fix(regulatory_alert): modify nightwork wording

public/index.html
https://trello.com/c/Qzdirapf/1288-ajout-balise-m%C3%A9ta-de-google-pour-r%C3%A9f%C3%A9rencement
=> feat(SEO): add google certification meta tag

common/utils/apiFragments.js, common/utils/apiQueries.js, web/controller/components/controlBulletin/ControlBulletinFormStep2.js, web/controller/components/controlBulletin/ControllerControlBulletin.js
https://trello.com/c/UEO53uvv/1188-ajout-de-linfo-immobilisation-du-v%C3%A9hicule
=> feat(control): option on control report for immobilized vehicle

web/pwa/components/PDFExport.js, web/pwa/screens/History.js
https://trello.com/c/ZJGXX94u/1262-etq-salari%C3%A9-la-modale-dexport-ne-retient-pas-mon-filtre-temporel
=> send initial min/max dates to pdf export modal

web/landing/sections/WebinarListSection.js
https://trello.com/c/Z3wh5772/1253-mise-%C3%A0-jour-titre-et-texte-section-webinaires-page-daccueil
=> update title and text webinars section

web/admin/components/C1BExport.js
https://trello.com/c/PAlGzv8b/1272-modifier-une-phrase-dans-la-modale-de-t%C3%A9l%C3%A9chargement-du-c1b-c%C3%B4t%C3%A9-gestionnaire
=> udpate text

web/landing/ResourcePage/ControllerResourcePage.js
https://trello.com/c/2r2gDsI2/1248-mettre-%C3%A0-jour-la-documentation-contr%C3%B4leur-avec-les-infos-sur-les-infractions
=> fix(controller): update wording for ressource page

common/utils/matomoTags.js, web/admin/panels/Company.js
Trello : https://trello.com/c/33LOeAaA/1221-suivi-des-clics-sur-longlet-certificat
=> feat(matomo): track click on certificate tab

web/landing/ResourcePage/RegulationDefinition.js, web/landing/ResourcePage/RegulationLegalArticle.js, web/landing/ResourcePage/RegulationRules.js
Trello : https://trello.com/c/Boh1PhMu/1255-remplacer-des-typos-et-du-wording-dans-le-parcours-controleur
PR back : https://github.com/MTES-MCT/mobilic-api/pull/299
=> fix(legal): typo

web/admin/panels/Validations.js
https://trello.com/c/IyT91boN/963-bug-mission-en-cours-et-message-stipule-activit%C3%A9s-termin%C3%A9es
=> fix(admin): ongoing activities helper text

web/admin/components/C1BExport.js
https://trello.com/c/GY3dTU0r/1230-maj-ui-modale-export-c1b-gestionnaire
=> fix(c1b_export): increase wording size

common/store/reducers/employment.js, common/store/reducers/root.js, common/store/store.js, common/utils/apiQueries.js, common/utils/loadUserData.js, web/admin/panels/Employees.js, web/common/EmploymentInfoCard.js, web/home/HideEmail.js, web/home/useUpdateHideEmail.js
https://trello.com/c/18CqYk0T/944-opt-in-salari%C3%A9-partage-mail-perso-avec-employeur
=> feat(hide-email): toggle button for employee

web/common/routes.js
Trello: https://trello.com/c/m3lzRvH2/1154-distinguer-le-lien-faq-dans-les-menus-gestionnaire-et-salari%C3%A9
=> feat(menu): use specific faq link for employee

web/control/components/UserReadTabs.js
- Bug that didn't display correctly the worker history when controlled and not login ;
=> hotfix(controller): display full worker history when controlled

web/admin/components/C1BExport.js
https://trello.com/c/XP0trUDk/1321-interface-gestionnaire-cocher-par-d%C3%A9faut-la-case-permettant-dobtenir-deux-fichiers-c1b-pour-une-seule-mission
=> fix(export-c1b): check by default export two versions

web/index.js, web/root.js
https://trello.com/c/8OsstTLe/1316-charger-crisp-pour-tous-les-utilisateurs
=> feat: load crisp by default

web/admin/panels/Company.js
https://trello.com/c/BwKLZcyJ/1351-mettre-%C3%A0-jour-lurl-lorsque-lon-change-donglet-dans-linterface-gestionnaire-pour-permettre-lutilisation-dactions-automatiques-de
=> feat(admin): change url on company tab

web/admin/components/MissionDetails/MissionDetails.js, web/pwa/components/MissionDetails.js, web/pwa/components/WorkTimeSummary.js, web/pwa/components/history/Day.js, web/pwa/components/history/Mission.js
Trello : https://trello.com/c/zJoFDNib/740-etq-salari%C3%A9-si-mon-gestionnaire-a-supprim%C3%A9-ma-mission-jai-toujours-acc%C3%A8s-%C3%A0-ma-saisie
=> Fix deleted missions v3

common/utils/api.js, web/root.js
Trello: https://trello.com/c/cN1kX3mF/1378-ajouter-le-dashboard-metabase-dans-les-demandes-crisp
=> feat(crisp): add mobilic id & metabase link

web/common/WayHeardOfMobilic.js
Trello : https://trello.com/c/qwgafpb6/1368-modifier-le-questionnaire-qui-appara%C3%AEt-au-moment-de-linscription-gestionnaire
=> feat(subscribe): add new option for subscribe questionnary

web/pwa/components/ActivityRevision/ActivityRevision.js, web/pwa/components/EndMission.js
Trello : https://trello.com/c/Sk1Rmd9b/1403-remplir-automatiquement-la-date-de-fin-lorsquon-modifie-une-activit%C3%A9
=> feat(edit activity): preset end time

common/utils/api.js
https://trello.com/c/Hsr2W40N/1414-page-blanche-lors-de-linvitation
=> Fix empty invitation page

common/utils/api.js
https://trello.com/c/Hsr2W40N/1414-page-blanche-lors-de-linvitation
=> Hotfix 29/02/2024

web/admin/components/ExcelExport.js
https://trello.com/c/rBAIX5bw/1114-erreur-dimport-sur-le-lien-de-v%C3%A9rification-excel-erreur-import-c1b
=> fix(admin): alert text do not modify - export excel

web/admin/components/MissionDetails/MissionDetailsLocations.js
https://trello.com/c/jH2wiKSW/1430-le-lieu-et-heure-de-fin-de-mission-ne-saffiche-plus
=> fix(mission): show mission end location

web/pwa/components/GeolocPermissionInfoModal.js
https://trello.com/c/LzBqKm0w/670-bug-ui-message-dinformation-%C3%A9cran-p%C3%A9dagogique-g%C3%A9oloc-sandbox
=> fix(geoloc): alert visibility

web/common/WayHeardOfMobilic.js
https://trello.com/c/uzum10oW/1422-retirer-deux-options-du-formulaire-dinscription
=> fix(way-heard): removed two items

web/common/routes.js, web/landing/footer.js, web/landing/legalNotices.js
https://trello.com/c/tkkzaOqL/1448-ajouter-les-mentions-l%C3%A9gales-sur-mobilic
=> feat(legal): legal notices page

web/landing/ResourcePage/ResourcePage.js
https://trello.com/c/a6uPKYHA/1429-mettre-%C3%A0-jour-les-notices-dutilisation-et-tutos-gestionnaire-et-salari%C3%A9-dans-la-documentation-ajout-des-cong%C3%A9s
=> feat(tutorial): update tutorial

web/pwa/components/ActivitySwitch.js
https://trello.com/c/2D61gf1u/1065-navigation-au-clavier-parcours-salari%C3%A9-pouvoir-cliquer-sur-les-3-boutons-principaux-travail-pause-et-autre-t%C3%A2che
=> feat(accessibility): can switch activity in driving screen with tab key

common/utils/cookie.js, common/utils/trackAds.js, web/root.js, web/signup/company/CompanySignup.js
https://trello.com/c/igzCP4dj/1423-les-conversions-ne-sont-pas-remont%C3%A9es-sur-google-ads
=> fix(tracker): always init google ads if consent granted

web/signup/AgentConnectCallback.js, web/signup/FranceConnectCallback.js
=> Revert "fix(FA-AC_connect): remove iss param from callbackUrl"

web/admin/components/C1BExport.js, web/home/AccountInfo/AlertEmailNotActivated.js, web/landing/accessibility.js, web/landing/footer.js, web/landing/gestionnaire/sections/OutroGestionnaire.js, web/landing/partners.js, web/signup/company/SelectSirenStep.js
Trello: [1450](https://trello.com/c/7QixZbhr/1450) et [1454](https://trello.com/c/2oW4l5O9/1454)
PR back: https://github.com/MTES-MCT/mobilic-api/pull/376
=> feat: update email to contact mobilic

common/utils/errors.js, web/common/CustomAlert.js, web/common/Snackbar.js
https://trello.com/c/HrM0rWfG/1376-modifier-le-message-derreur-lors-de-la-cr%C3%A9ation-dun-compte-contr%C3%B4leur-via-mcp
=> feat(controller): improve login error message

web/controller/components/details/ControllerControlDrawer.js, web/controller/components/noLic/ControllerControlNoLicDrawer.js, web/controller/utils/ControlDrawer.js
https://trello.com/c/3wRkKORa/1463-ajuster-le-titre-des-pages
J'ai pensé modifier usePageTitle dans un premier temps mais j'ai trouvé dommage de le rendre compliqué pour un cas particulier
=> update page title when opening control

common/utils/apiQueries.js, web/common/SignFiles.js, web/controller/components/details/ControllerControlExportMenu.js, web/controller/components/modals/ControllerExportC1BAll.js, web/controller/components/modals/ControllerExportC1BOne.js, web/modals.js
https://trello.com/c/xF6ugjwk/1132-export-c1b-depuis-la-vue-de-chaque-contr%C3%B4le
=> feat(control): export c1b file on control page

web/pwa/components/history/Mission.js
https://trello.com/c/4StTqIis/1543-remettre-la-bonne-couleur-des-lignes-dans-le-d%C3%A9tail-par-mission
=> less dark background

web/admin/components/C1BExport.js
https://trello.com/c/9xlZlPv6/1548-modifier-coquilles-modale-t%C3%A9l%C3%A9chargement-c1b-c%C3%B4t%C3%A9-gestionnaire
=> fixed two typos

common/utils/apiFragments.js, common/utils/apiQueries.js, web/admin/components/BusinessDropdown.js, web/admin/panels/Employees.js, web/common/useUpdateBusiness.js
https://trello.com/c/d81fQfSc/698-conception-tech-etq-gestionnaire-je-voudrais-pouvoir-s%C3%A9lectionner-le-type-dactivit%C3%A9-de-mes-salari%C3%A9s
Scénario 1
=> feat(business): admin can update employees business type

common/utils/regulation/alertTypes.js, web/control/components/RegulatoryAlert.js
https://trello.com/c/lkPnqoKo/1280-ajouter-le-natinf-11289-aux-infractions
=> feat(regulation): display max weekly work alert NATINF 11289

common/utils/expenditures.js, web/landing/ResourcePage/RegulationDefinition.js
https://trello.com/c/g5dOFLgh/1558
=> fix: rename 'découché' to 'découcher'

web/admin/components/UpdateCompanyBusinessTypeModal.js, web/common/BusinessType.js, web/common/MandatoryField.js, web/signup/company/SelectSiretsStep.js, web/signup/company/SubmitStep.js
Cette release est faite suite à une erreur de déploiement sur la prod, la recette de certains tickets n'a pas encore été faite et sera traitée par la suite.
https://trello.com/c/AqmimNel/1260-int%C3%A9grer-lensemble-des-seuils-aux-seuils-r%C3%A9glementaires
https://trello.com/c/lkPnqoKo/1280-ajouter-le-natinf-11289-aux-infractions
https://trello.com/c/g5dOFLgh/1558-corriger-lorthographe-de-d%C3%A9couch%C3%A9-dans-les-frais
=> Release 15/07/2024

web/signup/AccountCreation.js, web/signup/EmailSelection.js
https://trello.com/c/OfXfqIyP/1580-etq-utilisateur-jai-le-choix-de-minscrire-%C3%A0-la-newsletter
=> feat(signup): change newsletter wording and checkbox behavior

web/admin/components/BatchInvite.js, web/landing/privacyPolicy.js
https://trello.com/c/M4rXkVXb/1588
https://trello.com/c/HSFzOsbW/1585
=> Feat: update privacy policy

package.json, web/index.js
https://trello.com/c/S66dZnqD/1587
=> Fix: iOS white screen

web/admin/panels/Employees.js
https://trello.com/c/0erbfoZQ/1562-bug-mailjet-et-creation-de-compte-via-linterface
=> fix(employement): formatting employee invitation email to lowercase

web/admin/panels/Employees.js
Fix suite à une erreur de la première PR front
https://trello.com/c/0erbfoZQ/1562-bug-mailjet-et-creation-de-compte-via-linterface
=> fix(invitation): correct function for lowercase format

package.json, web/index.js
https://app.gitbook.com/o/-MMKfijmgB1Sviz-n2vh/s/-MaXamkHibni8siT6EUO/le-produit-mobilic/release-notes#id-01-08-2024
=> release 01/08/2024

web/landing/ResourcePage/ResourcePage.js
https://trello.com/c/EW7iZJhb/1596
=> fix(doc): update notice link

web/admin/components/ExcelExport.js
https://trello.com/c/EW7iZJhb/1596-mettre-%C3%A0-jour-les-liens-des-notices-dutilisation-des-pages-documentation
=> Release 12/08/2024

common/utils/loadUserData.js, web/common/EmploymentInfoCard.js, web/home/HideEmail.js
https://trello.com/c/UevkAwn0/1584-permettre-au-salari%C3%A9-de-voir-le-ou-les-types-dactivit%C3%A9-qui-lui-sont-attribu%C3%A9s
=> get business from back - display in mes Info - styling

web/landing/ResourcePage/FaqCard.js, web/landing/ResourcePage/RegulationDrawer.js, web/landing/ResourcePage/RegulationLegalArticle.js, web/landing/ResourcePage/RegulationPage.js, web/landing/ResourcePage/RegulationRules.js
https://trello.com/c/52rFpJHc/1583
J'en ai profité pour utiliser des `<p>` au lieu des `<span>` et `<br/>` pour l'accessibilité
=> feat(doc): update rules description

common/utils/apiQueries.js, web/pwa/modals/RejectedCguModals.js, web/root.js
https://trello.com/c/Ep5GdzkI/1517-back-t%C3%A9l%C3%A9chargement-donn%C3%A9es-utilisateurs
=> feat(data_export): full data history export when deleting account

web/control/components/AlertGroup.js, web/control/components/AlertsInHistory.js, web/control/components/RegulatoryAlert.js, web/control/components/UserReadAlerts.js, web/control/components/UserReadHistory.js, web/controller/components/details/ControllerControlDetails.js, web/pwa/components/history/Day.js, web/pwa/components/history/DaySummary.js, web/pwa/components/history/Week.js, web/pwa/screens/History.js, web/regulatory/DayRegulatoryAlerts.js, web/regulatory/GenericRegulatoryAlerts.js, web/regulatory/WeekRegulatoryAlerts.js
https://trello.com/c/WydBS36g/1616-corriger-les-d%C3%A9passements-de-seuils-de-longlet-historique-dun-contr%C3%B4le
=> Fix(controls): display observed infractions in History tab of a control

common/utils/time.js, web/pwa/screens/History.js
https://trello.com/c/WydBS36g/1616-corriger-les-d%C3%A9passements-de-seuils-de-longlet-historique-dun-contr%C3%B4le
=> fix(alerts): allow 3 hours to consider it's the same day or not

web/landing/ResourcePage/RegulationRules.js
https://trello.com/c/WwdgopVM/1623-modifier-une-phrase-de-la-page-r%C3%A9glementation
=> feat(legal_rules): modify legal rules wording

common/utils/apiQueries.js, common/utils/time.js, web/admin/components/EmployeeFilter.js, web/admin/panels/Validations.js, web/admin/store/reducers/sync.js, web/control/components/AlertGroup.js, web/control/components/AlertsInHistory.js, web/control/components/RegulatoryAlert.js, web/control/components/UserReadAlerts.js, web/control/components/UserReadHistory.js, web/controller/components/details/ControllerControlDetails.js, web/landing/ResourcePage/RegulationRules.js, web/pwa/components/history/Day.js, web/pwa/components/history/DaySummary.js, web/pwa/components/history/Week.js, web/pwa/screens/History.js, web/regulatory/DayRegulatoryAlerts.js, web/regulatory/GenericRegulatoryAlerts.js, web/regulatory/WeekRegulatoryAlerts.js
https://trello.com/c/WwdgopVM/1623-modifier-deux-phrases-de-la-page-r%C3%A9glementation
https://trello.com/c/dVH2JRvh/1268-ne-plus-voir-les-salari%C3%A9s-d%C3%A9tach%C3%A9s-dans-mes-listes-salari%C3%A9s-dans-les-saisies-%C3%A0-valider
=> Release 02/10/2024

web/admin/components/ExpendituresCard.js, web/admin/components/MissionDetails/MissionDetailsStyle.js, web/admin/components/Setting.js, web/admin/panels/CertificationPanel/CertificationCriteriaGlobalResult.js, web/admin/panels/Settings.js, web/pwa/components/ActivityList.js, web/pwa/components/SimplerRegulationCheck.js, web/pwa/modals/FirstActivitySelectionModal.js, web/pwa/screens/History.js, web/pwa/screens/MissionReview.js, web/regulatory/RegulatoryText.js
https://trello.com/c/gwkpK7UQ/1068-ajuster-les-niveaux-de-contrastes
=> Feat: adjust contrast

web/admin/components/AugmentedTable.js
https://trello.com/c/o7yIKnIR/1624
=> fix(admin): sort vehicle by usual name

web/home/AccountInfo/AccountInfo.js, web/home/AccountInfo/BecomeAdmin.js
https://trello.com/c/sHBp2qFe/1092-etq-salari%C3%A9-je-ne-peux-pas-cr%C3%A9er-une-entreprise
=> display button if user is not an admin

common/utils/apiQueries.js, common/utils/businessTypes.js, web/admin/components/AugmentedTable.js, web/admin/modals/C1BExportModal.js, web/admin/modals/ExcelExportModal.js, web/admin/panels/Activities.js, web/common/BusinessType.js, web/common/hooks/useGetUsersSinceDate.js, web/control/components/RegulatoryAlert.js, web/home/AccountInfo/AccountInfo.js, web/home/AccountInfo/BecomeAdmin.js, web/landing/ResourcePage/RegulationPage.js, web/landing/ResourcePage/RegulationRules.js
https://trello.com/c/yKTaZNbE/1626-ajouter-les-seuils-du-t3p-taxi-vtc
https://trello.com/c/aUTn3aMB/1281-modifier-les-explications-du-natinf-13152
https://trello.com/c/Drb8yjQ4/1630-mettre-%C3%A0-jour-les-textes-de-la-page-r%C3%A9glementation-avec-les-infos-sur-le-t3p
https://trello.com/c/G7EcFUCB/1621-ajouter-les-salari%C3%A9s-d%C3%A9tach%C3%A9s-dans-la-modale-dexport
https://trello.com/c/sHBp2qFe/1092-etq-salari%C3%A9-je-ne-peux-pas-cr%C3%A9er-une-entreprise
https://trello.com/c/o7yIKnIR/1624-bug-daffichage-lors-du-tri-de-la-colonne-non-usuel-de-longlet-v%C3%A9hicule
=> Release 28/10/2024

common/utils/theme.js, web/admin/assets/admin.scss, web/admin/components/AugmentedTable.js, web/admin/components/AugmentedTableRow.js
https://trello.com/c/TRDvWDM7/1537
=> Fix table accessibility

web/controller/components/controlBulletin/ControlBulletinFormStep2.js
https://trello.com/c/NGvKhm5t/1565
=> feat(bdc): use numeric keyboard for license

web/landing/footer.js
https://trello.com/c/aMdr9eva/1651-mettre-%C3%A0-jour-le-logo-et-le-nom-du-minist%C3%A8re-dans-le-footer
=> fix(footer): changed ministry name in footer

common/utils/apiQueries.js, web/control/components/UserReadInfo.js
https://trello.com/c/TsHKeInB/1649-lorsquun-contr%C3%B4le-mobilic-est-cr%C3%A9%C3%A9-enregistrer-le-type-dactivit%C3%A9-dans-le-contr%C3%B4le-et-ne-plus-le-modifier-par-la-suite
=> feat(controls): display current mission business type in control

web/controller/components/controlBulletin/ControlBulletinFormStep3.js, web/controller/components/noQRCode/noLic/ControllerControlNoLic.js, web/controller/components/noQRCode/noLic/ControllerControlNoLicDrawer.js
https://trello.com/c/2hv9MCpS/1664
=> feat(control): disable infraction edition for no lic controls

web/home/AccountInfo/AccountInfo.js, web/home/AccountInfo/BecomeAdmin.js
https://trello.com/c/C9p3fr03/1669-modifier-le-texte-pr%C3%A9cisant-quun-utilisateur-ne-peut-pas-saisir-de-temps-de-travail-car-il-nest-pas-rattach%C3%A9-%C3%A0-une-entreprie
=> fix(informations): wording no employments warning + become admin button

web/landing/partners.js
https://trello.com/c/yKpQAQJR/1661-le-bouton-devenir-partenaire-de-la-page-partenaires-ne-fonctionne-plus
=> fix(partners): fixed two buttons become partner

web/common/WayHeardOfMobilic.js, web/signup/AccountCreation.js
https://trello.com/c/XOKyFCi0/1665-rendre-obligatoire-le-champ-comment-avez-vous-connu-mobilic-de-linscription-gestionnaire
=> feat(admin_subscription): mandatory way of heard field

web/common/AlertEmailDelay.js, web/common/ButtonGoHome.js, web/landing/components/WebinarList.js, web/signup/Complete.js
https://trello.com/c/stpfzHXN/1642-ajouter-le-bloc-webinaires-sur-le-dernier-%C3%A9cran-de-linscription
=> feat(signup): show webinars at end of account creation

web/common/routes.js, web/landing/cgu.js, web/landing/footer.js, web/pwa/modals/AcceptCguModal.js
delete route /cgu
footer cgu is an external link to cgus
cgu modal at signing has an external link to cgus
https://trello.com/c/qNePT2nP/1682-bug-daffichage-des-cgu-sur-desktop
=> refacto(cgu):

web/controller/components/details/ControllerControlExportMenu.js, web/controller/components/details/ControllerControlHeader.js, web/controller/components/noQRCode/noLic/ControllerControlNoLicDrawer.js
https://trello.com/c/2fxpjGgP/858-etq-contr%C3%B4leur-je-peux-exporter-les-donn%C3%A9es-dun-contr%C3%B4le-lic-papier-pas-de-lic-et-les-infractions-relev%C3%A9es-au-format-excel
=> feat(controls): enable export excel for all controls

web/controller/components/home/ControllerHome.js, web/controller/components/home/ControllerHomeCard.js
https://trello.com/c/ND8LtGKc/1672-indiquer-aux-contrôleurs-lexistence-du-parcours-lic-papier
=> feat(controller): badge to show new feature - refacto / style controller home page

common/utils/apiQueries.js, web/controller/components/noQRCode/noLic/ControllerControlNoLicInformations.js
https://trello.com/c/YeNRUAKW/1689-contrôles-lic-papier-et-pas-de-lic-ajouter-le-type-dactivité-dans-longlet-informations
=> fix(control): display activity type in information tab for no lic / lic papier

web/controller/components/details/ControllerControlExportMenu.js, web/controller/components/details/ControllerControlHeader.js, web/controller/components/noQRCode/noLic/ControllerControlNoLicDrawer.js
Reverts MTES-MCT/mobilic#626
https://trello.com/c/2fxpjGgP/858-etq-contrôleur-je-peux-exporter-les-données-dun-contrôle-lic-papier-pas-de-lic-et-les-infractions-relevées-au-format-excel
=> Revert "Revert "feat(controls): enable export excel for all controls""

web/landing/ResourcePage/RegulationRules.js
https://trello.com/c/cigkdkeo/1912-petites-modifs-des-seuils-réglementaires-dans-la-page-réglementation
=> fix(regulations): add a sentence, modify hours regulations helper texts

web/home/InfoField.js
https://trello.com/c/fOzxUkfI/1927-adapter-le-champ-adresse-email-dans-la-page-mes-informations
=> fix(home): when content too long, display ellipsis

web/common/EmploymentInfoCard.js
https://trello.com/c/Du90GeEw/1937-bug-longlet-informations-du-détail-dun-contrôle-ne-sadapte-plus-à-lécran
=> fix(controls): information tab fix when admin email is too long

web/login/login-controller.js
https://trello.com/c/mMimLYut/1959-ajout-dun-message-pour-pr%C3%A9venir-que-la-connexion-controleur-est-impossible
=> Fix(cerbere): add warning message for controller to tell connexion is impossible

web/login/login-controller.js
https://trello.com/c/mMimLYut/1959-ajout-dun-message-pour-pr%C3%A9venir-que-la-connexion-controleur-est-impossible?search_id=485f8eea-59ff-4965-8a01-83b258e7803d
=> fix(cerbere): remove warning message for controller

common/utils/regulation/alertTypes.js, web/control/components/RegulatoryAlert.js
https://trello.com/c/XmB38ix8/1322-probl%C3%A8me-natinf-il-y-a-d%C3%A9sormais-un-natinf-commun-pour-le-non-respect-du-temps-de-pause-et-les-d%C3%A9passements-de-la-dur%C3%A9e-maximale
=> feat(natinf-35187): update display sentences for natinf-35187

common/utils/regulation/alertTypes.js, web/pwa/components/SimplerRegulationCheck.js
https://trello.com/c/XmB38ix8/1322-probl%C3%A8me-natinf-il-y-a-d%C3%A9sormais-un-natinf-commun-pour-le-non-respect-du-temps-de-pause-et-les-d%C3%A9passements-de-la-dur%C3%A9e-maximale
=> fix(regulations): split enoughBreak regulation check in two Notices in employee history view

web/signup/AccountCreation.js
https://trello.com/c/4pU2Ahze/1984
=> feat(signup): add phone number for employees

common/utils/apiFragments.js, common/utils/apiQueries.js
https://trello.com/c/AUCSnI1Y/1993-validation-automatique-des-missions-par-le-salari%C3%A9
=> feat(auto-validations): query isAuto from validations

web/common/InfoCard.js, web/control/components/AlertsInHistory.js, web/control/components/UserReadInfo.js, web/pwa/components/ActivityList.js, web/pwa/components/history/Day.js, web/pwa/components/history/DaySummary.js, web/pwa/components/history/Mission.js, web/pwa/components/history/Week.js
https://trello.com/c/c9pYRPos/2059-mettre-%C3%A0-jour-les-options-de-r%C3%A9ponse-%C3%A0-la-question-comment-avez-vous-connu-mobilic-dans-le-formulaire-dinscription
https://trello.com/c/Oyh8wpGd/2038-bdc-lors-des-2e-%C3%A9tape-et-3e-%C3%A9tapes-de-cr%C3%A9ation-du-bulletin-de-contr%C3%B4le-on-arrive-en-bas-de-la-page
https://trello.com/c/ptyyUF2f/2067-mise-%C3%A0-jour-de-lintitul%C3%A9-du-champ-nombre-de-salari%C3%A9s-lors-de-linscription-gestionnaire
https://trello.com/c/NQL0ptfe/2061-am%C3%A9liorer-les-temps-de-r%C3%A9ponse-du-chargement-gestionnaire
=> Release 27/05/2025

web/common/routes.js, web/controller/components/help/ModalHelpController.js, web/controller/components/home/ControllerHelpCard.js
https://trello.com/c/rHCQPDnO/2103-supprimer-tchap-de-linterface-contrôleur
=> Remove tchap from controller interface

common/assets/styles/root.scss, web/pwa/components/MissionValidations.js
https://trello.com/c/UXElGFi7/1992-refonte-des-alertes-de-validation-des-missions
=> FIX(auto-valiation)/carousel-notification-style

web/control/VerifyXlsxSignature.js
https://trello.com/c/zaolbHPb/2124-modifier-le-texte-du-message-qui-saffiche-sur-le-lien-de-v%C3%A9rification-des-fichiers-excel-en-cas-de-fichier-ne-provenant-pas-de-m
=> fix(xlsx_file): modify wording for integrity error

web/common/ButtonGoHome.js, web/signup/ActivateEmail.js
https://trello.com/c/1pPof9U0/2113-etq-gestionnaire-si-jai-d%C3%A9j%C3%A0-valid%C3%A9-mon-adresse-mail-je-dois-arriver-sur-lespace-de-gestion-dentreprise-%C3%A0-la-fin-du-parcours-din
=> feat(admin_sginup): modify route after signup to admin instead of home

web/admin/panels/CertificationPanel/CertificateCriteriaTable.js, web/common/hooks/useCompanyCertification.js
https://trello.com/c/pIGEcqEt/2247-probl%C3%A8me-daffichage-crit%C3%A8res-de-certification-dans-longlet-certificat
=> fix(certificat): change default value to '-' with tooltip when not certified
