- .gitignore
- README.md
- nginx/base_conf/base_conf.erb
- nginx/base_conf/mime.types
- package.json
- scripts/start_nginx.sh
- servers.conf.erb
Permet de faire tourner le front end en local dans les mêmes conditions qu'en prod, c'est-à-dire avec un serveur Nginx qui va notamment permettre de proxy les requêtes `/api` vers le bon backend.
Pour réaliser ça j'ai plus ou moins copié ce que faisait le [buildpack Scalingo](https://github.com/Scalingo/nginx-buildpack).
* Le fichier `nginx/base_conf/base_conf.erb` est une copie de leur template de config (https://github.com/Scalingo/nginx-buildpack/blob/master/config/nginx.conf.erb)
* Le script `scripts/start_nginx.sh` génère des fichiers de config à partir des templates (`nginx/base_conf/base_conf.erb` et `servers.conf.erb`) et des variablesrequises (REACT_APP_API_HOST, PORT, ...), puis lance un serveur nginx à partir de cette config.
* Une nouvelle commande `yarn build-with-nginx` …
> Local Nginx server with prod conf

- web/landing/root.js
https://trello.com/c/dB1vtxqa/434-supprimer-la-r%C3%A9f%C3%A9rence-au-transport-sanitaire-sur-la-landing
> Remove "Ambulance" from landing page.

- common/utils/apiQueries.js
- common/utils/loadUserData.js
- common/utils/store.js
- web/common/Confirmation.js
- web/pwa/components/MissionDetails.js
- web/pwa/components/history/Day.js
- web/pwa/components/history/Mission.js
Maintenant que la validation du salarié est bloquante côté back, càd qu'il ne peut plus modifier les données de la mission après validation (https://github.com/MTES-MCT/mobilic-api/pull/25), les actions de modification ne sont plus montrées dans le front :
* ajout/édition d'activités
* modification de frais
* modification du véhicule
* modification du kilométrage
* changement d'équipe
> Remove actions in mission review after employee validation

- common/utils/apiQueries.js
- common/utils/mission.js
- web/admin/components/MissionDetails.js
Mission created by admin should be editable even when not all workers have validated them.
> Fix for readOnly boolean in mission drawer.

- web/common/EmploymentInfoCard.js
Lorsqu'un employé devait valider son rattachement, l'affichage était cassé, particulièrement sur téléphone.
Cette PR corrige cet affichage :
> Better layout for employment validation

- common/utils/errors.js
https://trello.com/c/qaYdRBQe/571-message-derreur-dans-le-cas-dun-enregistrement-dactivit%C3%A9-dans-le-futur
Si l'heure du téléphone d'un utilisateur et sen avance, il ne pourra pas renseigner son temps dans Mobilic car on considèrera qu'il tente d'enregistrer du temps de travail dans le futur.
Avant cette PR, il n'y avait pas de message explicite expliquant à l'utilisateur d'où vient le problème.
La PR du back est ici : https://github.com/MTES-MCT/mobilic-api/pull/56
> Add explicit error message when trying to record an activity in the future

- web/home/RedeemInvite.js
When accepting an invitation via the email link, we should update it in the store, and not create a new one.
https://trello.com/c/E4ifs3x8/584-invitation-en-double-apr%C3%A8s-acceptation-dans-le-mail
> Prevent displaying an invitation twice when accepting it via email

- web/control/UserRead.js
- web/control/components/UserReadInfo.js
https://trello.com/c/TykoFhYU/627-r%C3%A9duire-lacc%C3%A8s-de-lhistorique-salari%C3%A9-contr%C3%B4l%C3%A9-en-bord-de-route-%C3%A0-28-jours-0
PR back : https://github.com/MTES-MCT/mobilic-api/pull/70
J'en ai profité pour corriger le nb de jours travaillés présentés sur la page d'info d'un contrôle, qui était jusqu'à présent en dur :sweat_smile:
> Change number of working days retrieved during a user control

- README.md
- package.json
- yarn.lock
https://trello.com/c/z5dz2cH3/660-la-console-playground-nest-plus-accessible
To fix playground, react & react-dom version were forced.
Old versions were used by `graphql-playground-react`
Additional work: 
* upgrade `sentry` (build was sometimes failing locally with a sentry error)
* remove `docusaurus` (not used and using an old react version aswell)
> Fix playground console

- common/utils/errors.js
- web/admin/components/TerminateEmployment.js
https://trello.com/c/T48Pkk5G/669-modifier-le-message-derreur-en-cas-de-non-succ%C3%A8s-du-d%C3%A9tachement-dun-salari%C3%A9
Message spécifique lorsqu'on veut terminer un rattachement dans le cas où :
- Le rattachement est déjà terminé
- Il existe des activités postérieures à la date de fin demandée
PR back : https://github.com/MTES-MCT/mobilic-api/pull/76
> Add specific error message when terminating employment

- common/utils/apiQueries.js
- web/admin/panels/Activities.js
- web/admin/store/reducers/root.js
- web/admin/store/reducers/users.js
https://trello.com/c/lU4UaLxt/675-etq-gestionnaire-je-ne-vois-plus-les-activit%C3%A9s-des-salari%C3%A9s-pour-qui-jai-mis-fin-au-rattachement
Il est désormais possible de voir les activités des salariés qui ne sont plus rattachés à la société.
PR Back : https://github.com/MTES-MCT/mobilic-api/pull/79
> Add the ability to see activities for user that have been deattached

- web/landing/ResourcePage/RegulationDefinition.js
- web/landing/ResourcePage/RegulationRules.js
https://trello.com/c/qdJbd962/672-correctif-des-heures-consid%C3%A9r%C3%A9es-comme-travail-de-nuit-pour-les-primes
Retrait de la définition des heures de nuit.
PR Back : https://github.com/MTES-MCT/mobilic-api/pull/87
> Remove night work definition

- common/utils/apiQueries.js
- web/admin/components/MissionDetails/MissionDetails.js
- web/admin/utils/missionActions.js
- web/pwa/components/ActivityRevision/ActivityRevision.js
https://trello.com/c/464VvOT9/738-etq-gestionnaire-je-veux-pouvoir-supprimer-une-mission
Lorsqu'un admin supprime une activité d'un utilisateur, et qu'il n'y a pas d'autres activités pour cet utilisateur dans la mission, on appelle un nouveau endpoint pour annuler toutes les activités de l'utilisateur pour la mission donnée, sans attendre le clic sur le bouton "valider les saisies"
PR Back : https://github.com/MTES-MCT/mobilic-api/pull/94
> Add call to cancel mission endpoint

- web/landing/ResourcePage/RegulationDefinition.js
- web/landing/ResourcePage/RegulationLegalArticle.js
- web/landing/ResourcePage/RegulationRules.js
https://trello.com/c/J7YzJJQR/747-ajouter-la-d%C3%A9finition-de-la-semaine-civile-%C3%A0-la-doc-au-niveau-du-repos-hebdo
> feat(doc): add calendar week definition

- common/utils/errors.js
https://trello.com/c/SljAfxUK/749-modifier-le-message-derreur-lorsque-lon-renseigne-une-date-ant%C3%A9rieure-au-rattachement-du-salari%C3%A9
PR back: https://github.com/MTES-MCT/mobilic-api/pull/102
> feat: error on activity creation before employment

- web/landing/components/WebinarList.js
even if title is very long
https://trello.com/c/cDe0aT5I/802-probl%C3%A8me-des-titres-de-webinaire-trop-longs-sur-la-page-daccueil
> style: display webinar correctly

- common/utils/addresses.js
- common/utils/time.js
- web/common/logEvent.js
- web/pwa/components/ContradictoryChanges.js
https://trello.com/c/OYwxpeAz/803-probl%C3%A8me-de-tournure-des-phrases-dans-lhistorique-de-saisie
Ne plus différencier les missions sur plusieurs jours / sur un seul jour. ==> Simplification des règles pour l'affichage de l'historique de saisie d'une mission.
> Change wording in mission history event

- common/utils/actions.js
- common/utils/loadUserData.js
- web/admin/components/WorkTimeDetails.js
- web/pwa/components/history/Day.js
- web/pwa/components/history/DaySummary.js
- web/pwa/components/history/Week.js
- web/regulatory/DayRegulatoryAlerts.js
- web/regulatory/GenericRegulatoryAlerts.js
- web/regulatory/WeekRegulatoryAlerts.js
https://trello.com/c/y2WYnLa8/972-ne-pas-r%C3%A9cup%C3%A9rer-les-seuils-c%C3%B4t%C3%A9-d%C3%A8s-le-login
Deux points peuvent encore être optimisés : 
- Lors de l'affichage du drawer workday d'un lundi dans l'interface admin, on fait deux fois la même requête pour récupérer les seuils du jour et de la semaine
- Dans la nouvelle interface contrôleur, on continue de charger tous les dépassements de seuils quand on ouvre le contrôle. On pourrait faire une modif d'API au niveau des permissions pour faire des appels à chaque fois comme dans l'historique salarié
> Do not load regulation computation on login as it would slow down the app

- common/utils/apiQueries.js
- common/utils/validation.js
- web/admin/panels/Company.js
- web/admin/store/reducers/root.js
- web/admin/store/reducers/sync.js
- web/common/EditableTextField.js
- Add api request for company name ;
- Add reducer for company name to change value in store ;
- Add genereic component for editable text field ;
https://trello.com/c/z4LXmpsp/1210-permettre-aux-gestionnaires-de-modifier-le-nom-de-leurs-entreprises
**Dépendance**
PR: https://github.com/MTES-MCT/mobilic-api/pull/272
> feat(Company): make editable company name

- web/pwa/screens/History.js
https://trello.com/c/I8lB9IzK/1284-vue-semaine-historique-salari%C3%A9-les-semaines-doivent-aller-du-lundi-au-dimanche
> fix(history): week label 'D - D + 7' -> 'D - D + 6'

- web/signup/AgentConnectCallback.js
- web/signup/FranceConnectCallback.js
Context :
- Library update 'panva' from A/F-connect add a query param 'iss' to the Service Provider (FS in fr) callbackUrl like Mobilic.
- This callbackUrl was used to make a POST request to /token path of A/F-connect, which led to error when login from controller users ;
- Remove 'iss' query param from France_connect callbackUrl for future update (send issuer in redirect uri is a standard) ;
Solution :
- Remove 'iss' query param from callbackUrl fixed the problem ;
https://trello.com/c/OI16HiaJ/1449-probl%C3%A8me-connexion-controleur
> fix(FA-AC_connect): remove iss param from callbackUrl

- web/control/components/Alerts/InfractionDay.js
- web/controller/components/details/ControllerControlHistory.js
- web/controller/components/scanQRCode/ControllerScanQRCode.js
**:warning: Variable d'environnement à mettre pour la MEP :  USER_CONTROL_HISTORY_DEPTH=56** 
[PR BACK](https://github.com/MTES-MCT/mobilic-api/pull/476)
https://trello.com/c/DV54hcgG/1670-faire-passer-le-nombre-de-jours-contr%C3%B4l%C3%A9s-%C3%A0-56
> feat(control_history): change control depth history

- web/controller/components/details/ControllerControlExportMenu.js
- web/controller/components/details/ControllerControlHeader.js
- web/controller/components/noQRCode/noLic/ControllerControlNoLicDrawer.js
> Revert "feat(controls): enable export excel for all controls"
